all:
	g++ main.cpp sitarski-hat.cpp brodnik-hat-a.cpp brodnik-hat-b.cpp

brd: # Background-rebuilding version
	g++ main.cpp sitarski-hat.cpp brodnik-hat-a-brd.cpp brodnik-hat-b-brd.cpp

clean:
	rm a.out

.PHONY: all clean
